version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - 127.0.0.1:5601:5601
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  tika-ocr-server:
    build:
      context: tika-ocr-server/
      dockerfile: Dockerfile
    container_name: tika-ocr-server
    ports:
    - 127.0.0.1:9998:9998
  scan-server:
#    ports:
#      - 127.0.0.1:5005:5005
    container_name: scan-server
    volumes:
      - type: bind
        source: ~/Documents/test
        target: /docs
    depends_on:
      - kibana
      - elasticsearch
      - tika-ocr-server
    environment:
      - elasticsearch.host=elasticsearch
      - TIKA_OCR_HOST=tika-ocr-server
    build:
      context: scan-server
      dockerfile: Dockerfile
volumes:
  data01:
    driver: local