spring:
  main:
    web-application-type: NONE
scanner:
  resources:
    - ${SCAN_DIR:file:/docs/}
elasticsearch:
  host: ${'elasticsearch.host':127.0.0.1}
  port: 9200
  schema: http
  index:
    name: documents
    recreate: true
    mappingsPath: classpath:/elasticsearch/index/documents/mappings.json
tika:
  url: http://${TIKA_OCR_HOST:127.0.0.1}:9998
  ocr:
    langs: eng+ita+fra+spa+deu+bel+rus+pol